api_platform:
    title: 'Api react'
    description: 'Symfony Api for my website'
    version: '0.0.1'
    show_webby: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
            items_per_page: 5
            client_enabled: true
            client_items_per_page: true

